[FIX] displays warnings for script correctly

diff --git a/script/chime b/script/chime
--- a/script/chime
+++ b/script/chime
@@ -24,7 +24,7 @@ source ./chime.conf
 function find_home() {
     path=`find ${USER_HOME} -maxdepth 1 -name $"${1}*"` 
     if [ -z ${path} ];then
-        echo $"Unable to find an avaible bin for $1"
+        echo $"Unable to find an avaible bin for $1" 1>&2
         exit 1;
     fi
     echo ${path}
